### ISSUE TITLE
product   好像不能使用汉字   

### ISSUE THREAD

**Issue by veeki** [hbh112233abc/ali-sms#1]
我调试了下  'TemplateParam' => json_encode($templateParam),  这里如果是汉字 params must be [a-zA-Z0-9] for verification sms

**Comment by hbh112233abc** [comment]
是啊 阿里云的短信模板占位符是要求英文加数字的

**Comment by sunjian2009** [comment]
> 是啊 阿里云的短信模板占位符是要求英文加数字的

那你不改改

**Comment by hbh112233abc** [comment]
额 原来是参数默认带product的问题,新版本已解决,谢谢
