### ISSUE TITLE
通过此包使用静态请求阿里SMS出现 params must be [a-zA-Z0-9] for verification sms

### ISSUE THREAD

**Issue by zg-626** [hbh112233abc/ali-sms#2]
使用链式调用正常
![image](https://user-images.githubusercontent.com/66429016/170678176-b52d7466-1e24-4cf5-af40-d5446981fdc3.png)
框架是tp6，php7.4

**Comment by hbh112233abc** [comment]
具体是怎么调用的呢? 可以加我qq 370520958

**Comment by hbh112233abc** [comment]
配置文件需要按短信模板进行配置,
问题原因:
短信模板仅有`code`参数,多配置了`project`参数,阿里云服务器报错
如果短信模板没有配置模板签名,也请不要配置模板签名`sign_name`
