### ISSUE TITLE
短信发送提示params must be [a-zA-Z0-9] for verification sms

### ISSUE THREAD

**Issue by yinwanjin** [hbh112233abc/ali-sms#3]
短信发送提示params must be [a-zA-Z0-9] for verification sms

配置文件部分内容如下：
'actions'       => [
        'register'        => [
            'sign_name'      => '注册验证',
            'template_code'  => 'SMS_136300056',
            'template_param' => [
                'code'    => '',
                'product' => '',
            ],
        ],
        'login'           => [
            'sign_name'      => '登录验证',
            'template_code'  => 'SMS_136300059',
            'template_param' => [
                'code'    => '',
                'product' => '',
            ],
        ],
        'change_password' => [
            'sign_name'      => '变更验证',
            'template_code'  => 'SMS_136300054',
            'template_param' => [
                'code'    => '',
                'product' => '',
            ],
        ],
    ],

控制器代码如下：

$mobile = input('phone');
$sms = new ThinkAliSms;
$res = $sms->register($mobile,['code'=>123456]);
var_dump($res);exit;

**Comment by hbh112233abc** [comment]
#2 请看一下这个哦
